"""empty message

Revision ID: 8f60a92f339f
Revises: 
Create Date: 2021-07-05 08:25:05.245557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f60a92f339f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id_classes', sa.Integer(), nullable=False),
    sa.Column('name_classes', sa.String(length=140), nullable=False),
    sa.Column('description_classes', sa.String(length=140), nullable=False),
    sa.PrimaryKeyConstraint('id_classes')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('accont_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id_class', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_class', sa.VARCHAR(length=140), autoincrement=False, nullable=False),
    sa.Column('description_class', sa.VARCHAR(length=140), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_class', name='class_pkey')
    )
    op.drop_table('users')
    op.drop_table('classes')
    # ### end Alembic commands ###
